doctrine:
  dbal:
    default_connection: user_data
    connections:
      user_data:
        url: '%env(default:vendor.dsn:VENDOR_DSN)%'
      app_data:
        url: '%env(default:vendor.sqlite_dsn:VENDOR_SQLITE_DSN)%'
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: user_data
        validate_xml_mapping: false
        mappings:
          Vendoring:
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            is_bundle: false
