parameters:
    vendoring.dsn: 'sqlite:%kernel.project_dir%/var/vendor.sqlite'
    vendor.dsn: '%vendoring.dsn%'

doctrine:
    dbal:
        url: '%env(default:vendor.dsn:VENDOR_DSN)%'
    orm:
        validate_xml_mapping: false
        mappings:
            Vendoring:
                type: attribute
                dir: '%kernel.project_dir%/src/Entity/Vendor'
                prefix: 'App\Vendoring\Entity\Vendor'
                is_bundle: false
