nelmio_api_doc:
    documentation:
        info:
            title: 'Vendoring API'
            description: 'Vendoring API surface'
            version: '1.0.0-rc'
    areas:
        default:
            path_patterns: ['^/api(?!/doc$)']