nelmio_api_doc:
    documentation:
        info:
            title: 'Vendoring API'
            description: 'Vendoring API surface'
            version: 'native'
    areas:
        default:
            path_patterns: ['^/api']