services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Vendoring\DataFixtures\VendorAccessBootstrapFixture: ~
    App\Vendoring\Command\VendorFixtureLoadCommand: ~

    App\Vendoring\Repository\Vendor\VendorRepository: ~
    App\Vendoring\Repository\Vendor\VendorUserAssignmentRepository: ~
    App\Vendoring\Repository\Vendor\VendorProfileRepository: ~
    App\Vendoring\Repository\Vendor\VendorMediaRepository: ~
    App\Vendoring\Repository\Vendor\VendorProfileAvatarRepository: ~
    App\Vendoring\Repository\Vendor\VendorProfileCoverRepository: ~
