services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Vendoring\DataFixtures\VendorAccessBootstrapFixture: ~
    App\Vendoring\Command\VendorFixtureLoadCommand: ~

    App\Vendoring\Repository\VendorRepository: ~
    App\Vendoring\Repository\VendorUserAssignmentRepository: ~
    App\Vendoring\Repository\VendorProfileRepository: ~
    App\Vendoring\Repository\VendorMediaRepository: ~
    App\Vendoring\Repository\VendorProfileAvatarRepository: ~
    App\Vendoring\Repository\VendorProfileCoverRepository: ~
