services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    # Generic resource scan
    App\Vendoring\:
        resource: '../src/'
        exclude: [ '../src/**/{Tests,Test}/' ]

    # Explicit service alias
    App\Vendoring\ServiceInterface\Core\VendorCoreServiceInterface:
        alias: App\Vendoring\Service\Core\VendorCoreService
